# Site settings
name: name
email: email
url: "https://kimpeter2018.github.io"
description: "A blog and a portfolio"
author: "kimpeter2018"
title: "Peter's Blog"
permalink: pretty
baseurl: /jekyll-theme-blogfolio
remote_theme : "lamccloskey/jekyll-theme-blogfolio"

# social
github:
  username: username

twitter:
  username: username
